
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 1277803295230001233
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Mystic Horizons is loading..."
	#The second line of text under the app name
	state = "Traveling to the Horizons"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is playing Mystic Horizons"
	#The seconds line of text under the app name
	state = "Chilling in the Main Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download Mystic Horizons Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking through the Horizons"
	#The second line of text under the app name
	state = "Browsing the Horizons"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is preparing for their journey"
	#The second line of text under the app name
	state = "Joining a World"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Conquering the Horizons"
	#The second line of text under the app name
	state = "Currently In %world%"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Conquering the Horizons. Together."
	#The second line of text under the app name
	state = "Playing on %servername%"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on a Realm."
	#The second line of text under the app name
	state = "Playing on %realmname%"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["smal"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Mystic Horizons"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = ["large"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "Download the Mystic Horizons Modpack Today!"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["small"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	#The buttons to display on Discord
	buttons = []

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"
		#The first line of text under the app name
		description = "%player% is in The Overworld"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["large"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Overworld"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["small"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"
		#The first line of text under the app name
		description = "%player% is in The Nether"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["large"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Nether"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["small"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"
		#The first line of text under the app name
		description = "%player% is in The End"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = ["large"]
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the End"
		#The Asset ID of the image to display as the small image
		smallImageKey = ["small"]
		#The text that gets displayed when the small image is hovered
		smallImageText = "%mods% mods installed"
		#The buttons to display on Discord
		buttons = []

