
["Enable or Disable Enchantments"]
	blessed_weapon = true
	decay = true
	Delicate = true
	Disengage = true
	dull_edge = true
	night_vision_ench = true
	water_breathing = true
	enhanced_efficiency = false
	"Enhanced Eff Arm Speed" = false
	enhanced_fire_aspect = true
	enhanced_handling = false
	enhanced_locomotion = false
	enhanced_protection = true
	enhanced_sharpness = false
	enhanced_thorns = false
	enhanced_unbreaking = false
	Excavator = true
	exploding_arrows = true
	Feasting = false
	final_stand = true
	fiery_thorns = true
	Frostbite = true
	ground_pound = true
	Heavy = true
	horse_shoe = false
	insta_kill = false
	jugger_nog = true
	lava_walker = true
	Lightning = true
	Lumberjack = false
	Magnetize = true
	midas_touch = true
	praise_the_sun = false
	reverse_knockback = true
	Savior = true
	Slowness = true
	Smelting = true
	Spilling = true
	Springy = true
	swimmers_boots = true
	tnt_miner = true
	Vitality = true
	Webbing = true
	Wither = true
	xp_mining_master = true
	"XP++ for Weapon" = true
	lifestealing_arrows = true

["Enable or disable explosions for enchantments"]
	ground_pound = true
	exploding_arrows = true
	Disengage = true
	tnt_miner = true

["Commands - /cleargrounditems"]
	"Enabled?" = false
	"Available in creative?" = false
	"Available in survival?" = false

